### ISSUE TITLE
Any benefits over amandasaurus / apache-log-parser?

### ISSUE THREAD

**Issue by carlinmack** [jwodder/apachelogs#3]
https://github.com/amandasaurus/apache-log-parser

They both seem to be quite similar, you could elevate this project by showing better performance or edge cases that are handled better by this project

**Comment by jwodder** [comment]
I believe this is the first I've heard of apache-log-parser.  Some of the features I see that apachelogs has that apache-log-parser doesn't seem to:

* apachelogs can piece together a full timestamp from various different `%{*}t` formats
* apachelogs allows looking up parsed fields by both name (`entry.request_time`) and directive (`entry.directives["%t"]`)
* apachelogs provides constants for some of the most common log formats
* apachelogs unescapes escape sequences in strings
* apachelogs supports a few directives that apache-log-parser does not, like `%{name}c` and `%{ms}T`

I'm not about to do performance testing, but both libraries work by converting log formats to regexes, so their performance is likely to be roughly the same.

**Comment by FelixSchwarz** [comment]
Also https://github.com/amandasaurus/apache-log-parser uses a GPL v3 license. This may or may not be a good thing depending on your project.
