### ISSUE TITLE
Parsing error logs

### ISSUE THREAD

**Issue by petroslamb** [jwodder/apachelogs#4]
Hi,

Great job with this package, used it to quickly parse large volumes of logs using Dask and it worked nicely out of the box.

I am now trying to parse error logs:
```
[Mon Feb 28 05:53:37.614199 2022] [php7:warn] [pid 527] [client 172.68.189.10:44562] PHP Warning:  Illegal string offset 'strictly_necessary' in /home/admin/web/best-eq.com/public_html/wp-content/themes/iqtest/page-templates/gdpr-consent.php on line 85, referer: https://www.best-eq.com/?gclid=EAIaIQobChMI9Mu077-h9gIVBZSzCh2dLwRKEAAYASAAEgLNnvD_BwE

```
Any tips on these?

**Comment by jwodder** [comment]
`apachelogs` is only for parsing access logs.  Error logs use a different set of format specifiers and are not supported by this library.
